# Site settings
title: "miotares - Bitcoin, Wirtschaft, Monero & Privacy"
description: "Willkommen auf miotares.com - Bitcoin, Wirtschaft, Monero und Privacy. Hier findest du meine Projekte, Artikel und Socials. Steuern sind Raub."
url: "https://miotares.com"
baseurl: ""

# SEO settings
lang: de
timezone: Europe/Berlin
future: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed

# Pagination
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title — Seite :num'

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "miotares"
      robots: "index,follow"
      twitter_card: "summary_large_image"